-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 16:59:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sportDB` ;

-- -----------------------------------------------------
-- Schema sportDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportDB` ;
USE `sportDB` ;

-- -----------------------------------------------------
-- Table `sportDB`.`SportsProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportDB`.`SportsProgram` (
  `idSportsProgram` INT NOT NULL AUTO_INCREMENT,
  `timeOfRest` DATETIME NULL,
  `numberReps` INT NULL,
  PRIMARY KEY (`idSportsProgram`),
  UNIQUE INDEX `idSportsProgram_UNIQUE` (`idSportsProgram` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportDB`.`NutritionalProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportDB`.`NutritionalProgram` (
  `idNutritionalProgram` INT NOT NULL AUTO_INCREMENT,
  `nbCalories` INT NULL,
  `nbProtein` INT NULL,
  `objective` VARCHAR(45) NULL,
  `nbCarbs` INT NULL,
  `nbFats` INT NULL,
  PRIMARY KEY (`idNutritionalProgram`),
  UNIQUE INDEX `idNutritionalProgram_UNIQUE` (`idNutritionalProgram` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportDB`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportDB`.`Journal` (
  `idJournal` INT NOT NULL AUTO_INCREMENT,
  `startSportsProgram` DATE NULL,
  `startNutritionalProgram` DATE NULL,
  `comments` VARCHAR(256) NULL,
  `User_iduser` INT NOT NULL,
  `SportsProgram_idSportsProgram` INT NULL,
  `NutritionalProgram_idNutritionalProgram` INT NULL,
  PRIMARY KEY (`idJournal`, `User_iduser`),
  UNIQUE INDEX `idJournal_UNIQUE` (`idJournal` ASC) VISIBLE,
  INDEX `fk_Journal_User1_idx` (`User_iduser` ASC) VISIBLE,
  INDEX `fk_Journal_SportsProgram1_idx` (`SportsProgram_idSportsProgram` ASC) VISIBLE,
  INDEX `fk_Journal_NutritionalProgram1_idx` (`NutritionalProgram_idNutritionalProgram` ASC) VISIBLE,
  UNIQUE INDEX `NutritionalProgram_idNutritionalProgram_UNIQUE` (`NutritionalProgram_idNutritionalProgram` ASC) VISIBLE,
  UNIQUE INDEX `SportsProgram_idSportsProgram_UNIQUE` (`SportsProgram_idSportsProgram` ASC) VISIBLE,
  CONSTRAINT `fk_Journal_User1`
    FOREIGN KEY (`User_iduser`)
    REFERENCES `sportDB`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Journal_SportsProgram1`
    FOREIGN KEY (`SportsProgram_idSportsProgram`)
    REFERENCES `sportDB`.`SportsProgram` (`idSportsProgram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Journal_NutritionalProgram1`
    FOREIGN KEY (`NutritionalProgram_idNutritionalProgram`)
    REFERENCES `sportDB`.`NutritionalProgram` (`idNutritionalProgram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportDB`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportDB`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `sportLevel` INT NULL,
  `objective` INT NULL,
  `weight` DOUBLE NULL,
  `daysAvailable` INT NULL,
  `Journal_idJournal` INT NOT NULL,
  `Journal_User_iduser` INT NOT NULL,
  PRIMARY KEY (`idClient`, `Journal_idJournal`, `Journal_User_iduser`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE,
  INDEX `fk_Client_Journal1_idx` (`Journal_idJournal` ASC, `Journal_User_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Journal1`
    FOREIGN KEY (`Journal_idJournal` , `Journal_User_iduser`)
    REFERENCES `sportDB`.`Journal` (`idJournal` , `User_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportDB`.`User` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NULL,
  `password` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NULL,
  `lastname` VARCHAR(256) NULL,
  `type` INT NOT NULL,
  `Client_idClient` INT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  INDEX `fk_User_Client_idx` (`Client_idClient` ASC) VISIBLE,
  UNIQUE INDEX `Client_idClient_UNIQUE` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_User_Client`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `sportDB`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportDB`.`Exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportDB`.`Exercise` (
  `idExercise` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `equipement` VARCHAR(256) NOT NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`idExercise`),
  UNIQUE INDEX `idExercise_UNIQUE` (`idExercise` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportDB`.`SportsProgram_has_Exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportDB`.`SportsProgram_has_Exercise` (
  `SportsProgram_idSportsProgram` INT NOT NULL,
  `Exercise_idExercise` INT NOT NULL,
  PRIMARY KEY (`SportsProgram_idSportsProgram`, `Exercise_idExercise`),
  INDEX `fk_SportsProgram_has_Exercise_Exercise1_idx` (`Exercise_idExercise` ASC) VISIBLE,
  INDEX `fk_SportsProgram_has_Exercise_SportsProgram1_idx` (`SportsProgram_idSportsProgram` ASC) VISIBLE,
  CONSTRAINT `fk_SportsProgram_has_Exercise_SportsProgram1`
    FOREIGN KEY (`SportsProgram_idSportsProgram`)
    REFERENCES `sportDB`.`SportsProgram` (`idSportsProgram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SportsProgram_has_Exercise_Exercise1`
    FOREIGN KEY (`Exercise_idExercise`)
    REFERENCES `sportDB`.`Exercise` (`idExercise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
